In [1]:
#!pip install torch numpy pandas matplotlib

In [2]:
import torch
import numpy as np

### Create a Numpy Array and compute 2 * x + y

In [3]:
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[7,8,9], [10,11,12]])
f = 2 * x + y
print(f)

[[ 9 12 15]
 [18 21 24]]


### Create a Tensor and compute 2 * x + y

In [4]:
x = torch.tensor([[1,2,3], [4,5,6]])
y = torch.tensor([[7,8,9], [10,11,12]])
f = 2 * x + y
print(f)

tensor([[ 9, 12, 15],
        [18, 21, 24]])


### Default Value Initialization

In [5]:
shape = [2,3]
xzeros = torch.zeros(shape)
xones = torch.ones(shape)
xrnd = torch.rand(shape)
print(xzeros)
print(xones)
print(xrnd)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.4622, 0.3364, 0.5483],
        [0.6094, 0.1233, 0.8801]])


### Bad way to set seed (global seed)

In [6]:
torch.manual_seed(42)
print(torch.rand([2,3]))

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


### Good way to set seed (using generator)

In [7]:
generator = torch.Generator().manual_seed(42)
print(torch.rand([2,3], generator=generator))

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


### Converting between tensors and NumPy arrays

In [8]:
xnp = np.array([[1,2,3],[4,5,6]])
f2 = y + xnp
print(f2)
f2.type()

tensor([[ 8, 10, 12],
        [14, 16, 18]])


'torch.LongTensor'

In [9]:
print(f.type()) # call the tensors type method
fnp = f.numpy() # create an array from the tensor
type(fnp) # uses the python inbuilt type()

torch.LongTensor


numpy.ndarray

In [10]:
xtensor = torch.tensor(xnp) # Don't use torch.from_numpy
print(xtensor)
print(xtensor.type())

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
torch.IntTensor


In [11]:
a = np.ones(3)                  
t = torch.tensor(a)      # create a tensor from an array
b = t.numpy()                # Create an array from the tensor
b[1] = 0                     # change a value in the array
print(a[1] == b[1])          # this value changes in the original array
print(t)                     # and also in the tensor - they share the same memory

False
tensor([1., 0., 1.], dtype=torch.float64)


### Data Types with Numpy and Pytorch

In [12]:
int8np = np.ones((2,3), dtype=np.int8)
bad = torch.tensor(int8np)
bad.type()

'torch.CharTensor'

In [13]:
not_so_good = torch.tensor(int8np.astype(np.int32))
not_so_good.type()

'torch.IntTensor'

In [14]:
good = torch.tensor(int8np, dtype=torch.int)
good.type()

'torch.IntTensor'

In [15]:
xint = torch.ones((2,3), dtype=torch.int)
xint.type()

'torch.IntTensor'

### Slicing and indexing and reshaping

In [16]:
print(x[0])
print(x[1][0:2])

tensor([1, 2, 3])
tensor([4, 5])


In [17]:
print(x)
print(x.size())
print(x.view(-1))
print(x.view(3,2))
print(x.view(6,1))

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [18]:
print(x.view(3,-1))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [19]:
print(x.transpose(0,1).size())
x.size()

torch.Size([3, 2])


torch.Size([2, 3])

In [20]:
a = torch.ones(1,2,3,4)
print(a.transpose(0,3).transpose(1,2).size())    #swaps axis in two steps
print(a.permute(3,2,1,0).size())                 #swaps all axis at once

torch.Size([4, 3, 2, 1])
torch.Size([4, 3, 2, 1])


In [21]:
print(x)
x.transpose_(1,0)
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


## 1. Load fish.csv and convert it to a tensor but ignore first column (Species). Split column "Width" as target variable and all other as input variables

In [22]:
import pandas as pd
fish_data = ...
fish_data

Ellipsis

In [23]:
X = fish_data[...].to_numpy() # Input variables (Numpy)
y = ... # Target Variable (Numpy)
X,y = torch.tensor(X), torch.tensor(y)

TypeError: 'ellipsis' object is not subscriptable

## 2. Split fish_data into training (n=127) and test set (n=32), randomly.

In [ ]:
generator = torch.Generator().manual_seed(42)
idx = ...
X_train, X_test = ...
y_train, y_test = ...

## 3.1. Normalize Dataset: X = (X - X.min) / (X.max - X.min)

In [ ]:
# Lambda Function
normalize = lambda z, z_min, z_max: ...

# Normalize X
x_min, x_max = ...
X_train_n, X_test_n = ...
# Normalize y
...

## 3.2. Standardize Dataset: X = (X - X.mean) / X.std

In [ ]:
# Lambda Function
standardize = lambda z, z_mean, z_std: ...

# Standardize X
x_mean, x_std = ...
X_train_s, X_test_s = ...
# Standardize y
...

## 4. Plot normalized, standardized vs non-normalized

In [ ]:
from matplotlib import pyplot as plt
# Create Subplot with two Figures
fig, (ax1, ax2) = plt.subplots(1, 2)
fig.set_figwidth(12)
fig.suptitle('Normalized Data on the right')

# Plot original data
ax1.set_ylim(0,100), ax1.set_xlim(0,100) # Set axis to be in range (0,100)
ax1.scatter(..., s=5) # Plot train data in blue
ax1.scatter(..., s=5) # Plot test data in orange

# Plot normalized data
ax2.set_ylim(0,1), ax2.set_xlim(0,1) # Set axis to be in range (0, 1)
...

In [ ]:
# Create Subplot with two Figures
fig, (ax1, ax2) = plt.subplots(1, 2)
fig.set_figwidth(12)
fig.suptitle('Standardized Data on the right')

# Plot original data
ax1.set_ylim(0,100), ax1.set_xlim(0,100) # Set axis to be in range (0,100)
ax1.scatter(..., s=5) # Plot train data in blue
ax1.scatter(..., s=5) # Plot test data in orange

# Plot standardized data
ax2.set_ylim(-3,3), ax2.set_xlim(-3,3) # Set axis to be in range (-3, 3)
...

## 5. Create Dummy Variables for Species

In [ ]:
# Create Dummy Variables
...